site_name: ABC
# repo_url: https://github.com/squidfunk/mkdocs-material  # uncomment this line and the build works

theme:
  name: material

extra:
  consent:
    title: Cookie consent
    description: hello world

nav:
  - Home: index.md
  - Dogs:
    - dogs/index.md
    - Golden Retrievers:
      - Golden Retrievers: dogs/golden-retrievers/index.md
      - Movies: dogs/golden-retrievers/movies.md
